---
detectors:
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true
  TooManyStatements:
    max_statements: 10

directories:
  spec:
    UtilityFunction:
      enabled: false

exclude_paths:
  - vendor
