Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

# Covered by reek
Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false


Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
