# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

installation:
  restore_cache: &restore_cache
    keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

  install_depencencies: &install_depencencies
    name: install dependencies
    command: |
      bundle install --jobs=4 --retry=3 --path vendor/bundle

  save_cache: &save_cache
    paths:
      - ./vendor/bundle
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}

rspec_steps: &rspec_steps
  - checkout
  - restore_cache: *restore_cache
  - run: *install_depencencies
  - save_cache: *save_cache
  - run:
      name: run rspec
      command: |
        mkdir /tmp/test-results
        TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
          circleci tests split --split-by=timings)"

        bundle exec rspec \
          --format progress \
          --format RspecJunitFormatter \
          --out /tmp/test-results/rspec.xml \
          --format progress \
          $TEST_FILES
  - store_test_results:
      path: /tmp/test-results
  - store_artifacts:
      path: /tmp/test-results
      destination: test-results


jobs:
  build-ruby-2-4:
    docker:
      - image: circleci/ruby:2.4
    steps: *rspec_steps
  build-ruby-2-5:
    docker:
      - image: circleci/ruby:2.5
    steps: *rspec_steps
  build-ruby-2-6:
    docker:
      - image: circleci/ruby:2.6
    steps: *rspec_steps
  lint-rubocop:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install_depencencies
      - save_cache: *save_cache
      - run:
          name: run rubocop
          command: bundle exec rubocop
  lint-reek:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *install_depencencies
      - save_cache: *save_cache
      - run:
          name: run reek
          command: bundle exec reek

workflows:
  version: 2
  build:
    jobs:
      - build-ruby-2-4
      - build-ruby-2-5
      - build-ruby-2-6
      - lint-rubocop
      - lint-reek

